### ISSUE TITLE
NPM audit security vulnerability around decompress

### ISSUE THREAD

**Issue by metatarz** [uoc-advanced-html-css/uoc-boilerplate#1]
**Description**

Running NPM audit against npm install outputs a security vulnerability around decompress which is a dependency of parcel-plugin-imagemin. 
Decompress is no longer mantained (last update was 3 years ago) so you would need to seek out an alternative dependency.

**Visual output of NPM audit**

![image](https://user-images.githubusercontent.com/32838302/76324354-29b5c580-62e6-11ea-9b5c-0584df61cfcd.png)

**Comment by jorditarrida** [comment]
Fixed in release 2.5.0, thanks :)
